/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const LoginIndexLazyImport = createFileRoute('/login/')()
const CreateEventIndexLazyImport = createFileRoute('/createEvent/')()
const EventEventIdIndexLazyImport = createFileRoute('/event/$eventId/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const CreateEventIndexLazyRoute = CreateEventIndexLazyImport.update({
  path: '/createEvent/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/createEvent/index.lazy').then((d) => d.Route),
)

const EventEventIdIndexLazyRoute = EventEventIdIndexLazyImport.update({
  path: '/event/$eventId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/event/$eventId/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/createEvent/': {
      preLoaderRoute: typeof CreateEventIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/event/$eventId/': {
      preLoaderRoute: typeof EventEventIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutLazyRoute,
  CreateEventIndexLazyRoute,
  LoginIndexLazyRoute,
  EventEventIdIndexLazyRoute,
])

/* prettier-ignore-end */
